In [2]:
import s3fs
import xarray as xr

In [3]:
bucket_src = "fcx-raw-data-temp"
# bucket_src = os.environ.get('SOURCE_BUCKET_NAME')
path_to_file="CRS/data"
# path_to_file = os.environ.get('PATH_TO_FEGS')
filename = "GOESR_CRS_L1B_20170517_v0.nc"
s3path = f"s3://{bucket_src}/{path_to_file}/{filename}"

In [4]:
s3path

's3://fcx-raw-data-temp/CRS/data/GOESR_CRS_L1B_20170517_v0.nc'

Mount S3 to local dir for direct load in xarray

In [5]:
fs = s3fs.S3FileSystem(anon=True)

In [6]:
fs.ls("fcx-raw-data-temp")

['fcx-raw-data-temp/ABI',
 'fcx-raw-data-temp/AVIRIS',
 'fcx-raw-data-temp/CPL',
 'fcx-raw-data-temp/CRS',
 'fcx-raw-data-temp/FEGS',
 'fcx-raw-data-temp/GLM',
 'fcx-raw-data-temp/ISS_LIS',
 'fcx-raw-data-temp/LIP',
 'fcx-raw-data-temp/LMA',
 'fcx-raw-data-temp/NAV_ER2',
 'fcx-raw-data-temp/S-HIS',
 'fcx-raw-data-temp/S-HIS2']

XARRAY

In [7]:
with fs.open(s3path, 'rb') as f:
    DS = xr.load_dataset(f, engine="scipy", drop_variables=['lon', 'lat'])

print(DS)

<xarray.Dataset>
Dimensions:    (time: 74467, range: 321)
Coordinates:
  * time       (time) timedelta64[ns] 02:28:33.001154400 ... 07:35:23.641778400
  * range      (range) float32 1.012e+03 1.087e+03 ... 2.492e+04 2.5e+04
Data variables: (12/16)
    gatesp     float32 74.95
    missing    float32 nan
    incid      (time) float32 0.0 9.969e+36 9.969e+36 ... 9.969e+36 9.969e+36
    roll       (time) float32 -1.341 -1.351 -1.307 ... -0.8147 -0.8147 -0.8147
    pitch      (time) float32 0.6765 0.7091 0.7446 ... -0.58 -0.5788 -0.5776
    track      (time) float32 -73.02 -73.02 -73.03 ... -74.68 -74.68 -74.68
    ...         ...
    wvel       (time) float32 5.708 5.718 5.711 ... -0.7386 -0.7345 -0.7305
    vacft      (time) float32 0.0 9.969e+36 9.969e+36 ... 9.969e+36 9.969e+36
    pwr        (time, range) float32 9.969e+36 9.969e+36 ... 9.969e+36 9.969e+36
    ref        (time, range) float32 -18.91 -21.36 -25.68 -17.94 ... nan nan nan
    dop        (time, range) float32 nan nan nan n

Dataset key properties

In [20]:
DS.coords

Coordinates:
  * time     (time) timedelta64[ns] 02:28:33.001154400 ... 07:35:23.641778400
  * range    (range) float32 1.012e+03 1.087e+03 1.162e+03 ... 2.492e+04 2.5e+04

In [27]:
DS.data_vars

Data variables:
    gatesp     float32 74.95
    missing    float32 nan
    incid      (time) float32 0.0 9.969e+36 9.969e+36 ... 9.969e+36 9.969e+36
    roll       (time) float32 -1.341 -1.351 -1.307 ... -0.8147 -0.8147 -0.8147
    pitch      (time) float32 0.6765 0.7091 0.7446 ... -0.58 -0.5788 -0.5776
    track      (time) float32 -73.02 -73.02 -73.03 ... -74.68 -74.68 -74.68
    height     (time) float32 1.749e+04 1.75e+04 ... 1.972e+04 1.972e+04
    head       (time) float32 286.7 286.7 286.7 286.7 ... 282.9 282.9 282.9
    evel       (time) float32 -183.4 -183.3 -183.3 ... -206.2 -206.2 -206.2
    nvel       (time) float32 56.0 55.99 55.95 55.96 ... 56.51 56.51 56.51 56.51
    wvel       (time) float32 5.708 5.718 5.711 ... -0.7386 -0.7345 -0.7305
    vacft      (time) float32 0.0 9.969e+36 9.969e+36 ... 9.969e+36 9.969e+36
    pwr        (time, range) float32 9.969e+36 9.969e+36 ... 9.969e+36 9.969e+36
    ref        (time, range) float32 -18.91 -21.36 -25.68 -17.94 ... nan nan 

In [29]:
DS.data_vars['ref']

<xarray.DataArray 'ref' (time: 74467, range: 321)>
array([[-18.905445, -21.356792, -25.679296, ...,        nan,        nan,
               nan],
       [-18.790478, -21.483028, -25.762894, ...,        nan,        nan,
               nan],
       [-18.927444, -21.16738 , -25.95508 , ...,        nan,        nan,
               nan],
       ...,
       [-40.323112, -36.766113, -38.658264, ...,        nan,        nan,
               nan],
       [-39.560387, -36.193375, -38.892174, ...,        nan,        nan,
               nan],
       [-38.19471 , -35.49832 , -38.108   , ...,        nan,        nan,
               nan]], dtype=float32)
Coordinates:
  * time     (time) timedelta64[ns] 02:28:33.001154400 ... 07:35:23.641778400
  * range    (range) float32 1.012e+03 1.087e+03 1.162e+03 ... 2.492e+04 2.5e+04
Attributes:
    long_name:  Radar Reflectivity
    units:      dBZ

In [33]:
DS.coords

Coordinates:
  * time     (time) timedelta64[ns] 02:28:33.001154400 ... 07:35:23.641778400
  * range    (range) float32 1.012e+03 1.087e+03 1.162e+03 ... 2.492e+04 2.5e+04

In [55]:
DS.coords['time']

<xarray.DataArray 'time' (time: 74467)>
array([ 8913001154400,  8913232040400,  8913208867200, ..., 27323186875199,
       27323413466399, 27323641778400], dtype='timedelta64[ns]')
Coordinates:
  * time     (time) timedelta64[ns] 02:28:33.001154400 ... 07:35:23.641778400
Attributes:
    long_name:  time in UTC

In [59]:
DS.coords['time'][74466]

<xarray.DataArray 'time' ()>
array(27323641778400, dtype='timedelta64[ns]')
Coordinates:
    time     timedelta64[ns] 07:35:23.641778400
Attributes:
    long_name:  time in UTC

In [69]:
import numpy as np
print(np.array([8913001154400], dtype='datetime64[ns]')) # last item in time coordinate
print(np.array([27323641778400], dtype='datetime64[ns]')) # 0th item in time coordinate

['1970-01-01T02:28:33.001154400']
['1970-01-01T07:35:23.641778400']


ROUGH (Conversion to Dataframe)

In [8]:
DS['ref']

<xarray.DataArray 'ref' (time: 74467, range: 321)>
array([[-18.905445, -21.356792, -25.679296, ...,        nan,        nan,
               nan],
       [-18.790478, -21.483028, -25.762894, ...,        nan,        nan,
               nan],
       [-18.927444, -21.16738 , -25.95508 , ...,        nan,        nan,
               nan],
       ...,
       [-40.323112, -36.766113, -38.658264, ...,        nan,        nan,
               nan],
       [-39.560387, -36.193375, -38.892174, ...,        nan,        nan,
               nan],
       [-38.19471 , -35.49832 , -38.108   , ...,        nan,        nan,
               nan]], dtype=float32)
Coordinates:
  * time     (time) timedelta64[ns] 02:28:33.001154400 ... 07:35:23.641778400
  * range    (range) float32 1.012e+03 1.087e+03 1.162e+03 ... 2.492e+04 2.5e+04
Attributes:
    long_name:  Radar Reflectivity
    units:      dBZ

In [35]:
DF = DS.to_dataframe()

In [39]:
DF

gatesp  missing         incid  \
time                      range                                            
0 days 02:28:33.001154400 1011.825012   74.949997      NaN  0.000000e+00   
                          1086.775024   74.949997      NaN  0.000000e+00   
                          1161.724976   74.949997      NaN  0.000000e+00   
                          1236.675049   74.949997      NaN  0.000000e+00   
                          1311.625000   74.949997      NaN  0.000000e+00   
...                                           ...      ...           ...   
0 days 07:35:23.641778400 24696.025391  74.949997      NaN  9.969210e+36   
                          24770.974609  74.949997      NaN  9.969210e+36   
                          24845.925781  74.949997      NaN  9.969210e+36   
                          24920.875000  74.949997      NaN  9.969210e+36   
                          24995.824219  74.949997      NaN  9.969210e+36   

                                            roll     pitch      track  \
time                      range                                         
0 days 02:28:33.001154400 1011.825012  -1.340926  0.676498 -73.015572   
                          1086.775024  -1.340926  0.676498 -73.015572   
                          1161.724976  -1.340926  0.676498 -73.015572   
                          1236.675049  -1.340926  0.676498 -73.015572   
                          1311.625000  -1.340926  0.676498 -73.015572   
...                                          ...       ...        ...   
0 days 07:35:23.641778400 24696.025391 -0.814730 -0.577582 -74.676399   
                          24770.974609 -0.814730 -0.577582 -74.676399   
                          24845.925781 -0.814730 -0.577582 -74.676399   
                          24920.875000 -0.814730 -0.577582 -74.676399   
                          24995.824219 -0.814730 -0.577582 -74.676399   

                                              height        head        evel  \
time                      range                                                
0 days 02:28:33.001154400 1011.825012   17494.628906  286.671875 -183.350861   
                          1086.775024   17494.628906  286.671875 -183.350861   
                          1161.724976   17494.628906  286.671875 -183.350861   
                          1236.675049   17494.628906  286.671875 -183.350861   
                          1311.625000   17494.628906  286.671875 -183.350861   
...                                              ...         ...         ...   
0 days 07:35:23.641778400 24696.025391  19721.119141  282.896454 -206.222198   
                          24770.974609  19721.119141  282.896454 -206.222198   
                          24845.925781  19721.119141  282.896454 -206.222198   
                          24920.875000  19721.119141  282.896454 -206.222198   
                          24995.824219  19721.119141  282.896454 -206.222198   

                                             nvel      wvel         vacft  \
time                      range                                             
0 days 02:28:33.001154400 1011.825012   56.001507  5.708407  0.000000e+00   
                          1086.775024   56.001507  5.708407  0.000000e+00   
                          1161.724976   56.001507  5.708407  0.000000e+00   
                          1236.675049   56.001507  5.708407  0.000000e+00   
                          1311.625000   56.001507  5.708407  0.000000e+00   
...                                           ...       ...           ...   
0 days 07:35:23.641778400 24696.025391  56.507305 -0.730452  9.969210e+36   
                          24770.974609  56.507305 -0.730452  9.969210e+36   
                          24845.925781  56.507305 -0.730452  9.969210e+36   
                          24920.875000  56.507305 -0.730452  9.969210e+36   
                          24995.824219  56.507305 -0.730452  9.969210e+36   

                                                 pwr        r

In [44]:
DF[['ref', 'roll']]

ref      roll
time                      range                            
0 days 02:28:33.001154400 1011.825012  -18.905445 -1.340926
                          1086.775024  -21.356792 -1.340926
                          1161.724976  -25.679296 -1.340926
                          1236.675049  -17.936014 -1.340926
                          1311.625000  -16.003502 -1.340926
...                                           ...       ...
0 days 07:35:23.641778400 24696.025391        NaN -0.814730
                          24770.974609        NaN -0.814730
                          24845.925781        NaN -0.814730
                          24920.875000        NaN -0.814730
                          24995.824219        NaN -0.814730

[23903907 rows x 2 columns]

ROUGH. (to demonstrate how dataset is created and its anatomy)

In [41]:
import numpy as np
import pandas as pd
temp = 15 + 8 * np.random.randn(2, 2, 3)
temp.shape


(2, 2, 3)

In [37]:

precip = 10 * np.random.rand(2, 2, 3)
precip

array([[[0.01852445, 4.19935478, 3.70577992],
        [7.13455703, 3.28248461, 4.10280432]],

       [[7.46978557, 2.95167903, 9.19852764],
        [7.13731837, 7.61124088, 3.00632479]]])

In [39]:

lon = [[-99.83, -99.32], [-99.79, -99.23]]

lat = [[42.25, 42.21], [42.63, 42.59]]
np.array(lat).shape

(2, 2)

In [43]:

# for real use cases, its good practice to supply array attributes such as
# units, but we won't bother here for the sake of brevity
ds = xr.Dataset(
    {
        "temperature": (["x", "y", "time"], temp),
        "precipitation": (["x", "y", "time"], precip),
    },
    coords={
        "lon": (["x", "y"], lon),
        "lat": (["x", "y"], lat),
        "time": pd.date_range("2014-09-06", periods=3),
        "reference_time": pd.Timestamp("2014-09-05"),
    },
)
ds

<xarray.Dataset>
Dimensions:         (x: 2, y: 2, time: 3)
Coordinates:
    lon             (x, y) float64 -99.83 -99.32 -99.79 -99.23
    lat             (x, y) float64 42.25 42.21 42.63 42.59
  * time            (time) datetime64[ns] 2014-09-06 2014-09-07 2014-09-08
    reference_time  datetime64[ns] 2014-09-05
Dimensions without coordinates: x, y
Data variables:
    temperature     (x, y, time) float64 35.54 12.56 9.264 ... 7.626 -2.722
    precipitation   (x, y, time) float64 0.01852 4.199 3.706 ... 7.611 3.006

In [45]:
ds.data_vars['precipitation']

<xarray.DataArray 'precipitation' (x: 2, y: 2, time: 3)>
array([[[0.01852445, 4.19935478, 3.70577992],
        [7.13455703, 3.28248461, 4.10280432]],

       [[7.46978557, 2.95167903, 9.19852764],
        [7.13731837, 7.61124088, 3.00632479]]])
Coordinates:
    lon             (x, y) float64 -99.83 -99.32 -99.79 -99.23
    lat             (x, y) float64 42.25 42.21 42.63 42.59
  * time            (time) datetime64[ns] 2014-09-06 2014-09-07 2014-09-08
    reference_time  datetime64[ns] 2014-09-05
Dimensions without coordinates: x, y

In [46]:
precip

array([[[0.01852445, 4.19935478, 3.70577992],
        [7.13455703, 3.28248461, 4.10280432]],

       [[7.46978557, 2.95167903, 9.19852764],
        [7.13731837, 7.61124088, 3.00632479]]])

In [50]:
cat = [[42.25, 42.21, 1],
       [42.63, 42.59, 1 ],
       [2,     2,     2]]
np.array(cat).shape 
# this means there are two dimensions, i.e. features VS no of data table. 
# There can be many features and there can be surely many data points for those features

(3, 3)

In [54]:
catss = [[[42.25, 42.21, 1],
        [42.63, 42.59, 1 ],
        [2,     2,     2]],
 
        [[42.25, 42.21, 1],
        [42.63, 42.59, 1 ],
        [2,     2,     2]]]
np.array(catss).shape 
# this means there are three dimensions, i.e. features VS no of data table. And on top of that, test_group(say) 
# There can be many features and there can be surely many data points for those features
# there are many test_groups conducted on various geographical locations, each seperated out say g1 and g2

(2, 3, 3)